// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: networking/v1alpha1/DataPush.proto

package com.lhotse.api.networking.v1alpha1;

public final class DataPushOuterClass {
  private DataPushOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DataPushOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lhotse.networking.v1alpha1.DataPush)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 数据类型
     * </pre>
     *
     * <code>.lhotse.networking.v1alpha1.DataPush.DataCategory category = 1 [json_name = "category"];</code>
     * @return The enum numeric value on the wire for category.
     */
    int getCategoryValue();
    /**
     * <pre>
     * 数据类型
     * </pre>
     *
     * <code>.lhotse.networking.v1alpha1.DataPush.DataCategory category = 1 [json_name = "category"];</code>
     * @return The category.
     */
    com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush.DataCategory getCategory();

    /**
     * <pre>
     * 数据
     * </pre>
     *
     * <code>.google.protobuf.Any data = 2 [json_name = "data"];</code>
     * @return Whether the data field is set.
     */
    boolean hasData();
    /**
     * <pre>
     * 数据
     * </pre>
     *
     * <code>.google.protobuf.Any data = 2 [json_name = "data"];</code>
     * @return The data.
     */
    com.google.protobuf.Any getData();
    /**
     * <pre>
     * 数据
     * </pre>
     *
     * <code>.google.protobuf.Any data = 2 [json_name = "data"];</code>
     */
    com.google.protobuf.AnyOrBuilder getDataOrBuilder();
  }
  /**
   * Protobuf type {@code lhotse.networking.v1alpha1.DataPush}
   */
  public static final class DataPush extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:lhotse.networking.v1alpha1.DataPush)
      DataPushOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DataPush.newBuilder() to construct.
    private DataPush(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DataPush() {
      category_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DataPush();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DataPush(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              category_ = rawValue;
              break;
            }
            case 18: {
              com.google.protobuf.Any.Builder subBuilder = null;
              if (data_ != null) {
                subBuilder = data_.toBuilder();
              }
              data_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(data_);
                data_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lhotse.api.networking.v1alpha1.DataPushOuterClass.internal_static_lhotse_networking_v1alpha1_DataPush_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lhotse.api.networking.v1alpha1.DataPushOuterClass.internal_static_lhotse_networking_v1alpha1_DataPush_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush.class, com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush.Builder.class);
    }

    /**
     * Protobuf enum {@code lhotse.networking.v1alpha1.DataPush.DataCategory}
     */
    public enum DataCategory
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SERVICE = 0;</code>
       */
      SERVICE(0),
      /**
       * <code>CLUSTER = 1;</code>
       */
      CLUSTER(1),
      /**
       * <code>ENDPOINT = 2;</code>
       */
      ENDPOINT(2),
      /**
       * <code>RULE = 3;</code>
       */
      RULE(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>SERVICE = 0;</code>
       */
      public static final int SERVICE_VALUE = 0;
      /**
       * <code>CLUSTER = 1;</code>
       */
      public static final int CLUSTER_VALUE = 1;
      /**
       * <code>ENDPOINT = 2;</code>
       */
      public static final int ENDPOINT_VALUE = 2;
      /**
       * <code>RULE = 3;</code>
       */
      public static final int RULE_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataCategory valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static DataCategory forNumber(int value) {
        switch (value) {
          case 0: return SERVICE;
          case 1: return CLUSTER;
          case 2: return ENDPOINT;
          case 3: return RULE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DataCategory>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DataCategory> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DataCategory>() {
              public DataCategory findValueByNumber(int number) {
                return DataCategory.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush.getDescriptor().getEnumTypes().get(0);
      }

      private static final DataCategory[] VALUES = values();

      public static DataCategory valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DataCategory(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:lhotse.networking.v1alpha1.DataPush.DataCategory)
    }

    public static final int CATEGORY_FIELD_NUMBER = 1;
    private int category_;
    /**
     * <pre>
     * 数据类型
     * </pre>
     *
     * <code>.lhotse.networking.v1alpha1.DataPush.DataCategory category = 1 [json_name = "category"];</code>
     * @return The enum numeric value on the wire for category.
     */
    @java.lang.Override public int getCategoryValue() {
      return category_;
    }
    /**
     * <pre>
     * 数据类型
     * </pre>
     *
     * <code>.lhotse.networking.v1alpha1.DataPush.DataCategory category = 1 [json_name = "category"];</code>
     * @return The category.
     */
    @java.lang.Override public com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush.DataCategory getCategory() {
      @SuppressWarnings("deprecation")
      com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush.DataCategory result = com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush.DataCategory.valueOf(category_);
      return result == null ? com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush.DataCategory.UNRECOGNIZED : result;
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.Any data_;
    /**
     * <pre>
     * 数据
     * </pre>
     *
     * <code>.google.protobuf.Any data = 2 [json_name = "data"];</code>
     * @return Whether the data field is set.
     */
    @java.lang.Override
    public boolean hasData() {
      return data_ != null;
    }
    /**
     * <pre>
     * 数据
     * </pre>
     *
     * <code>.google.protobuf.Any data = 2 [json_name = "data"];</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.Any getData() {
      return data_ == null ? com.google.protobuf.Any.getDefaultInstance() : data_;
    }
    /**
     * <pre>
     * 数据
     * </pre>
     *
     * <code>.google.protobuf.Any data = 2 [json_name = "data"];</code>
     */
    @java.lang.Override
    public com.google.protobuf.AnyOrBuilder getDataOrBuilder() {
      return getData();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (category_ != com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush.DataCategory.SERVICE.getNumber()) {
        output.writeEnum(1, category_);
      }
      if (data_ != null) {
        output.writeMessage(2, getData());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (category_ != com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush.DataCategory.SERVICE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, category_);
      }
      if (data_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getData());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush)) {
        return super.equals(obj);
      }
      com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush other = (com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush) obj;

      if (category_ != other.category_) return false;
      if (hasData() != other.hasData()) return false;
      if (hasData()) {
        if (!getData()
            .equals(other.getData())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CATEGORY_FIELD_NUMBER;
      hash = (53 * hash) + category_;
      if (hasData()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code lhotse.networking.v1alpha1.DataPush}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lhotse.networking.v1alpha1.DataPush)
        com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPushOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lhotse.api.networking.v1alpha1.DataPushOuterClass.internal_static_lhotse_networking_v1alpha1_DataPush_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lhotse.api.networking.v1alpha1.DataPushOuterClass.internal_static_lhotse_networking_v1alpha1_DataPush_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush.class, com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush.Builder.class);
      }

      // Construct using com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        category_ = 0;

        if (dataBuilder_ == null) {
          data_ = null;
        } else {
          data_ = null;
          dataBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lhotse.api.networking.v1alpha1.DataPushOuterClass.internal_static_lhotse_networking_v1alpha1_DataPush_descriptor;
      }

      @java.lang.Override
      public com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush getDefaultInstanceForType() {
        return com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush.getDefaultInstance();
      }

      @java.lang.Override
      public com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush build() {
        com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush buildPartial() {
        com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush result = new com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush(this);
        result.category_ = category_;
        if (dataBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = dataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush) {
          return mergeFrom((com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush other) {
        if (other == com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush.getDefaultInstance()) return this;
        if (other.category_ != 0) {
          setCategoryValue(other.getCategoryValue());
        }
        if (other.hasData()) {
          mergeData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int category_ = 0;
      /**
       * <pre>
       * 数据类型
       * </pre>
       *
       * <code>.lhotse.networking.v1alpha1.DataPush.DataCategory category = 1 [json_name = "category"];</code>
       * @return The enum numeric value on the wire for category.
       */
      @java.lang.Override public int getCategoryValue() {
        return category_;
      }
      /**
       * <pre>
       * 数据类型
       * </pre>
       *
       * <code>.lhotse.networking.v1alpha1.DataPush.DataCategory category = 1 [json_name = "category"];</code>
       * @param value The enum numeric value on the wire for category to set.
       * @return This builder for chaining.
       */
      public Builder setCategoryValue(int value) {
        
        category_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 数据类型
       * </pre>
       *
       * <code>.lhotse.networking.v1alpha1.DataPush.DataCategory category = 1 [json_name = "category"];</code>
       * @return The category.
       */
      @java.lang.Override
      public com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush.DataCategory getCategory() {
        @SuppressWarnings("deprecation")
        com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush.DataCategory result = com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush.DataCategory.valueOf(category_);
        return result == null ? com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush.DataCategory.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 数据类型
       * </pre>
       *
       * <code>.lhotse.networking.v1alpha1.DataPush.DataCategory category = 1 [json_name = "category"];</code>
       * @param value The category to set.
       * @return This builder for chaining.
       */
      public Builder setCategory(com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush.DataCategory value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        category_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 数据类型
       * </pre>
       *
       * <code>.lhotse.networking.v1alpha1.DataPush.DataCategory category = 1 [json_name = "category"];</code>
       * @return This builder for chaining.
       */
      public Builder clearCategory() {
        
        category_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Any data_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> dataBuilder_;
      /**
       * <pre>
       * 数据
       * </pre>
       *
       * <code>.google.protobuf.Any data = 2 [json_name = "data"];</code>
       * @return Whether the data field is set.
       */
      public boolean hasData() {
        return dataBuilder_ != null || data_ != null;
      }
      /**
       * <pre>
       * 数据
       * </pre>
       *
       * <code>.google.protobuf.Any data = 2 [json_name = "data"];</code>
       * @return The data.
       */
      public com.google.protobuf.Any getData() {
        if (dataBuilder_ == null) {
          return data_ == null ? com.google.protobuf.Any.getDefaultInstance() : data_;
        } else {
          return dataBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 数据
       * </pre>
       *
       * <code>.google.protobuf.Any data = 2 [json_name = "data"];</code>
       */
      public Builder setData(com.google.protobuf.Any value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
          onChanged();
        } else {
          dataBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * 数据
       * </pre>
       *
       * <code>.google.protobuf.Any data = 2 [json_name = "data"];</code>
       */
      public Builder setData(
          com.google.protobuf.Any.Builder builderForValue) {
        if (dataBuilder_ == null) {
          data_ = builderForValue.build();
          onChanged();
        } else {
          dataBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * 数据
       * </pre>
       *
       * <code>.google.protobuf.Any data = 2 [json_name = "data"];</code>
       */
      public Builder mergeData(com.google.protobuf.Any value) {
        if (dataBuilder_ == null) {
          if (data_ != null) {
            data_ =
              com.google.protobuf.Any.newBuilder(data_).mergeFrom(value).buildPartial();
          } else {
            data_ = value;
          }
          onChanged();
        } else {
          dataBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * 数据
       * </pre>
       *
       * <code>.google.protobuf.Any data = 2 [json_name = "data"];</code>
       */
      public Builder clearData() {
        if (dataBuilder_ == null) {
          data_ = null;
          onChanged();
        } else {
          data_ = null;
          dataBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * 数据
       * </pre>
       *
       * <code>.google.protobuf.Any data = 2 [json_name = "data"];</code>
       */
      public com.google.protobuf.Any.Builder getDataBuilder() {
        
        onChanged();
        return getDataFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 数据
       * </pre>
       *
       * <code>.google.protobuf.Any data = 2 [json_name = "data"];</code>
       */
      public com.google.protobuf.AnyOrBuilder getDataOrBuilder() {
        if (dataBuilder_ != null) {
          return dataBuilder_.getMessageOrBuilder();
        } else {
          return data_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : data_;
        }
      }
      /**
       * <pre>
       * 数据
       * </pre>
       *
       * <code>.google.protobuf.Any data = 2 [json_name = "data"];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getData(),
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        return dataBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:lhotse.networking.v1alpha1.DataPush)
    }

    // @@protoc_insertion_point(class_scope:lhotse.networking.v1alpha1.DataPush)
    private static final com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush();
    }

    public static com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DataPush>
        PARSER = new com.google.protobuf.AbstractParser<DataPush>() {
      @java.lang.Override
      public DataPush parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DataPush(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DataPush> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DataPush> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.lhotse.api.networking.v1alpha1.DataPushOuterClass.DataPush getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lhotse_networking_v1alpha1_DataPush_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lhotse_networking_v1alpha1_DataPush_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"networking/v1alpha1/DataPush.proto\022\032lh" +
      "otse.networking.v1alpha1\032\031google/protobu" +
      "f/any.proto\"\305\001\n\010DataPush\022M\n\010category\030\001 \001" +
      "(\01621.lhotse.networking.v1alpha1.DataPush" +
      ".DataCategoryR\010category\022(\n\004data\030\002 \001(\0132\024." +
      "google.protobuf.AnyR\004data\"@\n\014DataCategor" +
      "y\022\013\n\007SERVICE\020\000\022\013\n\007CLUSTER\020\001\022\014\n\010ENDPOINT\020" +
      "\002\022\010\n\004RULE\020\003BD\n\"com.lhotse.api.networking" +
      ".v1alpha1Z\036lhotse/api/networking/v1alpha" +
      "1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_lhotse_networking_v1alpha1_DataPush_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lhotse_networking_v1alpha1_DataPush_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lhotse_networking_v1alpha1_DataPush_descriptor,
        new java.lang.String[] { "Category", "Data", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
