// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        (unknown)
// source: networking/v1alpha1/DataPush.proto

package v1alpha1

import (
	any "github.com/golang/protobuf/ptypes/any"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataPush_DataCategory int32

const (
	DataPush_SERVICE  DataPush_DataCategory = 0
	DataPush_CLUSTER  DataPush_DataCategory = 1
	DataPush_ENDPOINT DataPush_DataCategory = 2
	DataPush_RULE     DataPush_DataCategory = 3
)

// Enum value maps for DataPush_DataCategory.
var (
	DataPush_DataCategory_name = map[int32]string{
		0: "SERVICE",
		1: "CLUSTER",
		2: "ENDPOINT",
		3: "RULE",
	}
	DataPush_DataCategory_value = map[string]int32{
		"SERVICE":  0,
		"CLUSTER":  1,
		"ENDPOINT": 2,
		"RULE":     3,
	}
)

func (x DataPush_DataCategory) Enum() *DataPush_DataCategory {
	p := new(DataPush_DataCategory)
	*p = x
	return p
}

func (x DataPush_DataCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataPush_DataCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_networking_v1alpha1_DataPush_proto_enumTypes[0].Descriptor()
}

func (DataPush_DataCategory) Type() protoreflect.EnumType {
	return &file_networking_v1alpha1_DataPush_proto_enumTypes[0]
}

func (x DataPush_DataCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataPush_DataCategory.Descriptor instead.
func (DataPush_DataCategory) EnumDescriptor() ([]byte, []int) {
	return file_networking_v1alpha1_DataPush_proto_rawDescGZIP(), []int{0, 0}
}

type DataPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category DataPush_DataCategory `protobuf:"varint,1,opt,name=category,proto3,enum=lhotse.networking.v1alpha1.DataPush_DataCategory" json:"category,omitempty"` // 数据类型
	Data     *any.Any              `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                                                                // 数据
}

func (x *DataPush) Reset() {
	*x = DataPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_networking_v1alpha1_DataPush_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPush) ProtoMessage() {}

func (x *DataPush) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1alpha1_DataPush_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPush.ProtoReflect.Descriptor instead.
func (*DataPush) Descriptor() ([]byte, []int) {
	return file_networking_v1alpha1_DataPush_proto_rawDescGZIP(), []int{0}
}

func (x *DataPush) GetCategory() DataPush_DataCategory {
	if x != nil {
		return x.Category
	}
	return DataPush_SERVICE
}

func (x *DataPush) GetData() *any.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_networking_v1alpha1_DataPush_proto protoreflect.FileDescriptor

var file_networking_v1alpha1_DataPush_proto_rawDesc = []byte{
	0x0a, 0x22, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x2f, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x44, 0x61, 0x74, 0x61, 0x50, 0x75, 0x73, 0x68, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x6c, 0x68, 0x6f, 0x74, 0x73, 0x65, 0x2e, 0x6e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31,
	0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc5, 0x01, 0x0a, 0x08,
	0x44, 0x61, 0x74, 0x61, 0x50, 0x75, 0x73, 0x68, 0x12, 0x4d, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x31, 0x2e, 0x6c, 0x68, 0x6f,
	0x74, 0x73, 0x65, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x76,
	0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x50, 0x75, 0x73, 0x68,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x08, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x40, 0x0a, 0x0c, 0x44, 0x61, 0x74, 0x61, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x10, 0x00, 0x12, 0x0b,
	0x0a, 0x07, 0x43, 0x4c, 0x55, 0x53, 0x54, 0x45, 0x52, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x45,
	0x4e, 0x44, 0x50, 0x4f, 0x49, 0x4e, 0x54, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x52, 0x55, 0x4c,
	0x45, 0x10, 0x03, 0x42, 0x1c, 0x5a, 0x1a, 0x6c, 0x68, 0x6f, 0x74, 0x73, 0x65, 0x2f, 0x6e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_networking_v1alpha1_DataPush_proto_rawDescOnce sync.Once
	file_networking_v1alpha1_DataPush_proto_rawDescData = file_networking_v1alpha1_DataPush_proto_rawDesc
)

func file_networking_v1alpha1_DataPush_proto_rawDescGZIP() []byte {
	file_networking_v1alpha1_DataPush_proto_rawDescOnce.Do(func() {
		file_networking_v1alpha1_DataPush_proto_rawDescData = protoimpl.X.CompressGZIP(file_networking_v1alpha1_DataPush_proto_rawDescData)
	})
	return file_networking_v1alpha1_DataPush_proto_rawDescData
}

var file_networking_v1alpha1_DataPush_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_networking_v1alpha1_DataPush_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_networking_v1alpha1_DataPush_proto_goTypes = []interface{}{
	(DataPush_DataCategory)(0), // 0: lhotse.networking.v1alpha1.DataPush.DataCategory
	(*DataPush)(nil),           // 1: lhotse.networking.v1alpha1.DataPush
	(*any.Any)(nil),            // 2: google.protobuf.Any
}
var file_networking_v1alpha1_DataPush_proto_depIdxs = []int32{
	0, // 0: lhotse.networking.v1alpha1.DataPush.category:type_name -> lhotse.networking.v1alpha1.DataPush.DataCategory
	2, // 1: lhotse.networking.v1alpha1.DataPush.data:type_name -> google.protobuf.Any
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_networking_v1alpha1_DataPush_proto_init() }
func file_networking_v1alpha1_DataPush_proto_init() {
	if File_networking_v1alpha1_DataPush_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_networking_v1alpha1_DataPush_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_networking_v1alpha1_DataPush_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_networking_v1alpha1_DataPush_proto_goTypes,
		DependencyIndexes: file_networking_v1alpha1_DataPush_proto_depIdxs,
		EnumInfos:         file_networking_v1alpha1_DataPush_proto_enumTypes,
		MessageInfos:      file_networking_v1alpha1_DataPush_proto_msgTypes,
	}.Build()
	File_networking_v1alpha1_DataPush_proto = out.File
	file_networking_v1alpha1_DataPush_proto_rawDesc = nil
	file_networking_v1alpha1_DataPush_proto_goTypes = nil
	file_networking_v1alpha1_DataPush_proto_depIdxs = nil
}
