// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: push/DataPush.proto

package com.lhotse.api.push;

public final class DataPush {
  private DataPush() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code lhotse.networking.v1alpha1.DataCategory}
   */
  public enum DataCategory
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DATA_CATEGORY_SERVICE = 0;</code>
     */
    DATA_CATEGORY_SERVICE(0),
    /**
     * <code>DATA_CATEGORY_CLUSTER = 1;</code>
     */
    DATA_CATEGORY_CLUSTER(1),
    /**
     * <code>DATA_CATEGORY_ENDPOINT = 2;</code>
     */
    DATA_CATEGORY_ENDPOINT(2),
    /**
     * <code>DATA_CATEGORY_RULE = 3;</code>
     */
    DATA_CATEGORY_RULE(3),
    /**
     * <code>DATA_CATEGORY_AGENT_META = 4;</code>
     */
    DATA_CATEGORY_AGENT_META(4),
    /**
     * <code>DATA_CATEGORY_AGENT_UPLOAD_STATUS = 5;</code>
     */
    DATA_CATEGORY_AGENT_UPLOAD_STATUS(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>DATA_CATEGORY_SERVICE = 0;</code>
     */
    public static final int DATA_CATEGORY_SERVICE_VALUE = 0;
    /**
     * <code>DATA_CATEGORY_CLUSTER = 1;</code>
     */
    public static final int DATA_CATEGORY_CLUSTER_VALUE = 1;
    /**
     * <code>DATA_CATEGORY_ENDPOINT = 2;</code>
     */
    public static final int DATA_CATEGORY_ENDPOINT_VALUE = 2;
    /**
     * <code>DATA_CATEGORY_RULE = 3;</code>
     */
    public static final int DATA_CATEGORY_RULE_VALUE = 3;
    /**
     * <code>DATA_CATEGORY_AGENT_META = 4;</code>
     */
    public static final int DATA_CATEGORY_AGENT_META_VALUE = 4;
    /**
     * <code>DATA_CATEGORY_AGENT_UPLOAD_STATUS = 5;</code>
     */
    public static final int DATA_CATEGORY_AGENT_UPLOAD_STATUS_VALUE = 5;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DataCategory valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static DataCategory forNumber(int value) {
      switch (value) {
        case 0: return DATA_CATEGORY_SERVICE;
        case 1: return DATA_CATEGORY_CLUSTER;
        case 2: return DATA_CATEGORY_ENDPOINT;
        case 3: return DATA_CATEGORY_RULE;
        case 4: return DATA_CATEGORY_AGENT_META;
        case 5: return DATA_CATEGORY_AGENT_UPLOAD_STATUS;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DataCategory>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        DataCategory> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DataCategory>() {
            public DataCategory findValueByNumber(int number) {
              return DataCategory.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.lhotse.api.push.DataPush.getDescriptor().getEnumTypes().get(0);
    }

    private static final DataCategory[] VALUES = values();

    public static DataCategory valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private DataCategory(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:lhotse.networking.v1alpha1.DataCategory)
  }

  /**
   * Protobuf enum {@code lhotse.networking.v1alpha1.PushStatus}
   */
  public enum PushStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PUSH_STATUS_OK = 0;</code>
     */
    PUSH_STATUS_OK(0),
    /**
     * <code>PUSH_STATUS_FAIL = 1;</code>
     */
    PUSH_STATUS_FAIL(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>PUSH_STATUS_OK = 0;</code>
     */
    public static final int PUSH_STATUS_OK_VALUE = 0;
    /**
     * <code>PUSH_STATUS_FAIL = 1;</code>
     */
    public static final int PUSH_STATUS_FAIL_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PushStatus valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static PushStatus forNumber(int value) {
      switch (value) {
        case 0: return PUSH_STATUS_OK;
        case 1: return PUSH_STATUS_FAIL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PushStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PushStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PushStatus>() {
            public PushStatus findValueByNumber(int number) {
              return PushStatus.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.lhotse.api.push.DataPush.getDescriptor().getEnumTypes().get(1);
    }

    private static final PushStatus[] VALUES = values();

    public static PushStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private PushStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:lhotse.networking.v1alpha1.PushStatus)
  }

  /**
   * <pre>
   * 推送动作
   * </pre>
   *
   * Protobuf enum {@code lhotse.networking.v1alpha1.PushAction}
   */
  public enum PushAction
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 全量
     * </pre>
     *
     * <code>PUSH_ACTION_FULL = 0;</code>
     */
    PUSH_ACTION_FULL(0),
    /**
     * <pre>
     * 增量
     * </pre>
     *
     * <code>PUSH_ACTION_INCREMENT = 1;</code>
     */
    PUSH_ACTION_INCREMENT(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * 全量
     * </pre>
     *
     * <code>PUSH_ACTION_FULL = 0;</code>
     */
    public static final int PUSH_ACTION_FULL_VALUE = 0;
    /**
     * <pre>
     * 增量
     * </pre>
     *
     * <code>PUSH_ACTION_INCREMENT = 1;</code>
     */
    public static final int PUSH_ACTION_INCREMENT_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PushAction valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static PushAction forNumber(int value) {
      switch (value) {
        case 0: return PUSH_ACTION_FULL;
        case 1: return PUSH_ACTION_INCREMENT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PushAction>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PushAction> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PushAction>() {
            public PushAction findValueByNumber(int number) {
              return PushAction.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.lhotse.api.push.DataPush.getDescriptor().getEnumTypes().get(2);
    }

    private static final PushAction[] VALUES = values();

    public static PushAction valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private PushAction(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:lhotse.networking.v1alpha1.PushAction)
  }

  public interface DataPushRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lhotse.networking.v1alpha1.DataPushRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 数据类型
     * </pre>
     *
     * <code>.lhotse.networking.v1alpha1.DataCategory category = 1 [json_name = "category"];</code>
     * @return The enum numeric value on the wire for category.
     */
    int getCategoryValue();
    /**
     * <pre>
     * 数据类型
     * </pre>
     *
     * <code>.lhotse.networking.v1alpha1.DataCategory category = 1 [json_name = "category"];</code>
     * @return The category.
     */
    com.lhotse.api.push.DataPush.DataCategory getCategory();

    /**
     * <pre>
     * 动作
     * </pre>
     *
     * <code>.lhotse.networking.v1alpha1.PushAction action = 2 [json_name = "action"];</code>
     * @return The enum numeric value on the wire for action.
     */
    int getActionValue();
    /**
     * <pre>
     * 动作
     * </pre>
     *
     * <code>.lhotse.networking.v1alpha1.PushAction action = 2 [json_name = "action"];</code>
     * @return The action.
     */
    com.lhotse.api.push.DataPush.PushAction getAction();

    /**
     * <pre>
     * 数据
     * </pre>
     *
     * <code>.google.protobuf.Any data = 3 [json_name = "data"];</code>
     * @return Whether the data field is set.
     */
    boolean hasData();
    /**
     * <pre>
     * 数据
     * </pre>
     *
     * <code>.google.protobuf.Any data = 3 [json_name = "data"];</code>
     * @return The data.
     */
    com.google.protobuf.Any getData();
    /**
     * <pre>
     * 数据
     * </pre>
     *
     * <code>.google.protobuf.Any data = 3 [json_name = "data"];</code>
     */
    com.google.protobuf.AnyOrBuilder getDataOrBuilder();
  }
  /**
   * <pre>
   * 推送请求
   * </pre>
   *
   * Protobuf type {@code lhotse.networking.v1alpha1.DataPushRequest}
   */
  public static final class DataPushRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:lhotse.networking.v1alpha1.DataPushRequest)
      DataPushRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DataPushRequest.newBuilder() to construct.
    private DataPushRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DataPushRequest() {
      category_ = 0;
      action_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DataPushRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DataPushRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              category_ = rawValue;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              action_ = rawValue;
              break;
            }
            case 26: {
              com.google.protobuf.Any.Builder subBuilder = null;
              if (data_ != null) {
                subBuilder = data_.toBuilder();
              }
              data_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(data_);
                data_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lhotse.api.push.DataPush.internal_static_lhotse_networking_v1alpha1_DataPushRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lhotse.api.push.DataPush.internal_static_lhotse_networking_v1alpha1_DataPushRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lhotse.api.push.DataPush.DataPushRequest.class, com.lhotse.api.push.DataPush.DataPushRequest.Builder.class);
    }

    public static final int CATEGORY_FIELD_NUMBER = 1;
    private int category_;
    /**
     * <pre>
     * 数据类型
     * </pre>
     *
     * <code>.lhotse.networking.v1alpha1.DataCategory category = 1 [json_name = "category"];</code>
     * @return The enum numeric value on the wire for category.
     */
    @java.lang.Override public int getCategoryValue() {
      return category_;
    }
    /**
     * <pre>
     * 数据类型
     * </pre>
     *
     * <code>.lhotse.networking.v1alpha1.DataCategory category = 1 [json_name = "category"];</code>
     * @return The category.
     */
    @java.lang.Override public com.lhotse.api.push.DataPush.DataCategory getCategory() {
      @SuppressWarnings("deprecation")
      com.lhotse.api.push.DataPush.DataCategory result = com.lhotse.api.push.DataPush.DataCategory.valueOf(category_);
      return result == null ? com.lhotse.api.push.DataPush.DataCategory.UNRECOGNIZED : result;
    }

    public static final int ACTION_FIELD_NUMBER = 2;
    private int action_;
    /**
     * <pre>
     * 动作
     * </pre>
     *
     * <code>.lhotse.networking.v1alpha1.PushAction action = 2 [json_name = "action"];</code>
     * @return The enum numeric value on the wire for action.
     */
    @java.lang.Override public int getActionValue() {
      return action_;
    }
    /**
     * <pre>
     * 动作
     * </pre>
     *
     * <code>.lhotse.networking.v1alpha1.PushAction action = 2 [json_name = "action"];</code>
     * @return The action.
     */
    @java.lang.Override public com.lhotse.api.push.DataPush.PushAction getAction() {
      @SuppressWarnings("deprecation")
      com.lhotse.api.push.DataPush.PushAction result = com.lhotse.api.push.DataPush.PushAction.valueOf(action_);
      return result == null ? com.lhotse.api.push.DataPush.PushAction.UNRECOGNIZED : result;
    }

    public static final int DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.Any data_;
    /**
     * <pre>
     * 数据
     * </pre>
     *
     * <code>.google.protobuf.Any data = 3 [json_name = "data"];</code>
     * @return Whether the data field is set.
     */
    @java.lang.Override
    public boolean hasData() {
      return data_ != null;
    }
    /**
     * <pre>
     * 数据
     * </pre>
     *
     * <code>.google.protobuf.Any data = 3 [json_name = "data"];</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.Any getData() {
      return data_ == null ? com.google.protobuf.Any.getDefaultInstance() : data_;
    }
    /**
     * <pre>
     * 数据
     * </pre>
     *
     * <code>.google.protobuf.Any data = 3 [json_name = "data"];</code>
     */
    @java.lang.Override
    public com.google.protobuf.AnyOrBuilder getDataOrBuilder() {
      return getData();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (category_ != com.lhotse.api.push.DataPush.DataCategory.DATA_CATEGORY_SERVICE.getNumber()) {
        output.writeEnum(1, category_);
      }
      if (action_ != com.lhotse.api.push.DataPush.PushAction.PUSH_ACTION_FULL.getNumber()) {
        output.writeEnum(2, action_);
      }
      if (data_ != null) {
        output.writeMessage(3, getData());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (category_ != com.lhotse.api.push.DataPush.DataCategory.DATA_CATEGORY_SERVICE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, category_);
      }
      if (action_ != com.lhotse.api.push.DataPush.PushAction.PUSH_ACTION_FULL.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, action_);
      }
      if (data_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getData());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.lhotse.api.push.DataPush.DataPushRequest)) {
        return super.equals(obj);
      }
      com.lhotse.api.push.DataPush.DataPushRequest other = (com.lhotse.api.push.DataPush.DataPushRequest) obj;

      if (category_ != other.category_) return false;
      if (action_ != other.action_) return false;
      if (hasData() != other.hasData()) return false;
      if (hasData()) {
        if (!getData()
            .equals(other.getData())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CATEGORY_FIELD_NUMBER;
      hash = (53 * hash) + category_;
      hash = (37 * hash) + ACTION_FIELD_NUMBER;
      hash = (53 * hash) + action_;
      if (hasData()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.lhotse.api.push.DataPush.DataPushRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lhotse.api.push.DataPush.DataPushRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lhotse.api.push.DataPush.DataPushRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lhotse.api.push.DataPush.DataPushRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lhotse.api.push.DataPush.DataPushRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lhotse.api.push.DataPush.DataPushRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lhotse.api.push.DataPush.DataPushRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lhotse.api.push.DataPush.DataPushRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lhotse.api.push.DataPush.DataPushRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.lhotse.api.push.DataPush.DataPushRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lhotse.api.push.DataPush.DataPushRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lhotse.api.push.DataPush.DataPushRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.lhotse.api.push.DataPush.DataPushRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 推送请求
     * </pre>
     *
     * Protobuf type {@code lhotse.networking.v1alpha1.DataPushRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lhotse.networking.v1alpha1.DataPushRequest)
        com.lhotse.api.push.DataPush.DataPushRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lhotse.api.push.DataPush.internal_static_lhotse_networking_v1alpha1_DataPushRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lhotse.api.push.DataPush.internal_static_lhotse_networking_v1alpha1_DataPushRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lhotse.api.push.DataPush.DataPushRequest.class, com.lhotse.api.push.DataPush.DataPushRequest.Builder.class);
      }

      // Construct using com.lhotse.api.push.DataPush.DataPushRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        category_ = 0;

        action_ = 0;

        if (dataBuilder_ == null) {
          data_ = null;
        } else {
          data_ = null;
          dataBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lhotse.api.push.DataPush.internal_static_lhotse_networking_v1alpha1_DataPushRequest_descriptor;
      }

      @java.lang.Override
      public com.lhotse.api.push.DataPush.DataPushRequest getDefaultInstanceForType() {
        return com.lhotse.api.push.DataPush.DataPushRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.lhotse.api.push.DataPush.DataPushRequest build() {
        com.lhotse.api.push.DataPush.DataPushRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.lhotse.api.push.DataPush.DataPushRequest buildPartial() {
        com.lhotse.api.push.DataPush.DataPushRequest result = new com.lhotse.api.push.DataPush.DataPushRequest(this);
        result.category_ = category_;
        result.action_ = action_;
        if (dataBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = dataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lhotse.api.push.DataPush.DataPushRequest) {
          return mergeFrom((com.lhotse.api.push.DataPush.DataPushRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lhotse.api.push.DataPush.DataPushRequest other) {
        if (other == com.lhotse.api.push.DataPush.DataPushRequest.getDefaultInstance()) return this;
        if (other.category_ != 0) {
          setCategoryValue(other.getCategoryValue());
        }
        if (other.action_ != 0) {
          setActionValue(other.getActionValue());
        }
        if (other.hasData()) {
          mergeData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lhotse.api.push.DataPush.DataPushRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lhotse.api.push.DataPush.DataPushRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int category_ = 0;
      /**
       * <pre>
       * 数据类型
       * </pre>
       *
       * <code>.lhotse.networking.v1alpha1.DataCategory category = 1 [json_name = "category"];</code>
       * @return The enum numeric value on the wire for category.
       */
      @java.lang.Override public int getCategoryValue() {
        return category_;
      }
      /**
       * <pre>
       * 数据类型
       * </pre>
       *
       * <code>.lhotse.networking.v1alpha1.DataCategory category = 1 [json_name = "category"];</code>
       * @param value The enum numeric value on the wire for category to set.
       * @return This builder for chaining.
       */
      public Builder setCategoryValue(int value) {
        
        category_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 数据类型
       * </pre>
       *
       * <code>.lhotse.networking.v1alpha1.DataCategory category = 1 [json_name = "category"];</code>
       * @return The category.
       */
      @java.lang.Override
      public com.lhotse.api.push.DataPush.DataCategory getCategory() {
        @SuppressWarnings("deprecation")
        com.lhotse.api.push.DataPush.DataCategory result = com.lhotse.api.push.DataPush.DataCategory.valueOf(category_);
        return result == null ? com.lhotse.api.push.DataPush.DataCategory.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 数据类型
       * </pre>
       *
       * <code>.lhotse.networking.v1alpha1.DataCategory category = 1 [json_name = "category"];</code>
       * @param value The category to set.
       * @return This builder for chaining.
       */
      public Builder setCategory(com.lhotse.api.push.DataPush.DataCategory value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        category_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 数据类型
       * </pre>
       *
       * <code>.lhotse.networking.v1alpha1.DataCategory category = 1 [json_name = "category"];</code>
       * @return This builder for chaining.
       */
      public Builder clearCategory() {
        
        category_ = 0;
        onChanged();
        return this;
      }

      private int action_ = 0;
      /**
       * <pre>
       * 动作
       * </pre>
       *
       * <code>.lhotse.networking.v1alpha1.PushAction action = 2 [json_name = "action"];</code>
       * @return The enum numeric value on the wire for action.
       */
      @java.lang.Override public int getActionValue() {
        return action_;
      }
      /**
       * <pre>
       * 动作
       * </pre>
       *
       * <code>.lhotse.networking.v1alpha1.PushAction action = 2 [json_name = "action"];</code>
       * @param value The enum numeric value on the wire for action to set.
       * @return This builder for chaining.
       */
      public Builder setActionValue(int value) {
        
        action_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 动作
       * </pre>
       *
       * <code>.lhotse.networking.v1alpha1.PushAction action = 2 [json_name = "action"];</code>
       * @return The action.
       */
      @java.lang.Override
      public com.lhotse.api.push.DataPush.PushAction getAction() {
        @SuppressWarnings("deprecation")
        com.lhotse.api.push.DataPush.PushAction result = com.lhotse.api.push.DataPush.PushAction.valueOf(action_);
        return result == null ? com.lhotse.api.push.DataPush.PushAction.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 动作
       * </pre>
       *
       * <code>.lhotse.networking.v1alpha1.PushAction action = 2 [json_name = "action"];</code>
       * @param value The action to set.
       * @return This builder for chaining.
       */
      public Builder setAction(com.lhotse.api.push.DataPush.PushAction value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        action_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 动作
       * </pre>
       *
       * <code>.lhotse.networking.v1alpha1.PushAction action = 2 [json_name = "action"];</code>
       * @return This builder for chaining.
       */
      public Builder clearAction() {
        
        action_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Any data_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> dataBuilder_;
      /**
       * <pre>
       * 数据
       * </pre>
       *
       * <code>.google.protobuf.Any data = 3 [json_name = "data"];</code>
       * @return Whether the data field is set.
       */
      public boolean hasData() {
        return dataBuilder_ != null || data_ != null;
      }
      /**
       * <pre>
       * 数据
       * </pre>
       *
       * <code>.google.protobuf.Any data = 3 [json_name = "data"];</code>
       * @return The data.
       */
      public com.google.protobuf.Any getData() {
        if (dataBuilder_ == null) {
          return data_ == null ? com.google.protobuf.Any.getDefaultInstance() : data_;
        } else {
          return dataBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 数据
       * </pre>
       *
       * <code>.google.protobuf.Any data = 3 [json_name = "data"];</code>
       */
      public Builder setData(com.google.protobuf.Any value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
          onChanged();
        } else {
          dataBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * 数据
       * </pre>
       *
       * <code>.google.protobuf.Any data = 3 [json_name = "data"];</code>
       */
      public Builder setData(
          com.google.protobuf.Any.Builder builderForValue) {
        if (dataBuilder_ == null) {
          data_ = builderForValue.build();
          onChanged();
        } else {
          dataBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * 数据
       * </pre>
       *
       * <code>.google.protobuf.Any data = 3 [json_name = "data"];</code>
       */
      public Builder mergeData(com.google.protobuf.Any value) {
        if (dataBuilder_ == null) {
          if (data_ != null) {
            data_ =
              com.google.protobuf.Any.newBuilder(data_).mergeFrom(value).buildPartial();
          } else {
            data_ = value;
          }
          onChanged();
        } else {
          dataBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * 数据
       * </pre>
       *
       * <code>.google.protobuf.Any data = 3 [json_name = "data"];</code>
       */
      public Builder clearData() {
        if (dataBuilder_ == null) {
          data_ = null;
          onChanged();
        } else {
          data_ = null;
          dataBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * 数据
       * </pre>
       *
       * <code>.google.protobuf.Any data = 3 [json_name = "data"];</code>
       */
      public com.google.protobuf.Any.Builder getDataBuilder() {
        
        onChanged();
        return getDataFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 数据
       * </pre>
       *
       * <code>.google.protobuf.Any data = 3 [json_name = "data"];</code>
       */
      public com.google.protobuf.AnyOrBuilder getDataOrBuilder() {
        if (dataBuilder_ != null) {
          return dataBuilder_.getMessageOrBuilder();
        } else {
          return data_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : data_;
        }
      }
      /**
       * <pre>
       * 数据
       * </pre>
       *
       * <code>.google.protobuf.Any data = 3 [json_name = "data"];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getData(),
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        return dataBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:lhotse.networking.v1alpha1.DataPushRequest)
    }

    // @@protoc_insertion_point(class_scope:lhotse.networking.v1alpha1.DataPushRequest)
    private static final com.lhotse.api.push.DataPush.DataPushRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.lhotse.api.push.DataPush.DataPushRequest();
    }

    public static com.lhotse.api.push.DataPush.DataPushRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DataPushRequest>
        PARSER = new com.google.protobuf.AbstractParser<DataPushRequest>() {
      @java.lang.Override
      public DataPushRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DataPushRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DataPushRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DataPushRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.lhotse.api.push.DataPush.DataPushRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DataPushResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lhotse.networking.v1alpha1.DataPushResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 状态
     * </pre>
     *
     * <code>.lhotse.networking.v1alpha1.PushStatus status = 1 [json_name = "status"];</code>
     * @return The enum numeric value on the wire for status.
     */
    int getStatusValue();
    /**
     * <pre>
     * 状态
     * </pre>
     *
     * <code>.lhotse.networking.v1alpha1.PushStatus status = 1 [json_name = "status"];</code>
     * @return The status.
     */
    com.lhotse.api.push.DataPush.PushStatus getStatus();

    /**
     * <pre>
     * 消息
     * </pre>
     *
     * <code>string message = 2 [json_name = "message"];</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <pre>
     * 消息
     * </pre>
     *
     * <code>string message = 2 [json_name = "message"];</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * <pre>
   * 推送结果
   * </pre>
   *
   * Protobuf type {@code lhotse.networking.v1alpha1.DataPushResponse}
   */
  public static final class DataPushResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:lhotse.networking.v1alpha1.DataPushResponse)
      DataPushResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DataPushResponse.newBuilder() to construct.
    private DataPushResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DataPushResponse() {
      status_ = 0;
      message_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DataPushResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DataPushResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lhotse.api.push.DataPush.internal_static_lhotse_networking_v1alpha1_DataPushResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lhotse.api.push.DataPush.internal_static_lhotse_networking_v1alpha1_DataPushResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lhotse.api.push.DataPush.DataPushResponse.class, com.lhotse.api.push.DataPush.DataPushResponse.Builder.class);
    }

    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    /**
     * <pre>
     * 状态
     * </pre>
     *
     * <code>.lhotse.networking.v1alpha1.PushStatus status = 1 [json_name = "status"];</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <pre>
     * 状态
     * </pre>
     *
     * <code>.lhotse.networking.v1alpha1.PushStatus status = 1 [json_name = "status"];</code>
     * @return The status.
     */
    @java.lang.Override public com.lhotse.api.push.DataPush.PushStatus getStatus() {
      @SuppressWarnings("deprecation")
      com.lhotse.api.push.DataPush.PushStatus result = com.lhotse.api.push.DataPush.PushStatus.valueOf(status_);
      return result == null ? com.lhotse.api.push.DataPush.PushStatus.UNRECOGNIZED : result;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object message_;
    /**
     * <pre>
     * 消息
     * </pre>
     *
     * <code>string message = 2 [json_name = "message"];</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 消息
     * </pre>
     *
     * <code>string message = 2 [json_name = "message"];</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (status_ != com.lhotse.api.push.DataPush.PushStatus.PUSH_STATUS_OK.getNumber()) {
        output.writeEnum(1, status_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (status_ != com.lhotse.api.push.DataPush.PushStatus.PUSH_STATUS_OK.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, status_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.lhotse.api.push.DataPush.DataPushResponse)) {
        return super.equals(obj);
      }
      com.lhotse.api.push.DataPush.DataPushResponse other = (com.lhotse.api.push.DataPush.DataPushResponse) obj;

      if (status_ != other.status_) return false;
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.lhotse.api.push.DataPush.DataPushResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lhotse.api.push.DataPush.DataPushResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lhotse.api.push.DataPush.DataPushResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lhotse.api.push.DataPush.DataPushResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lhotse.api.push.DataPush.DataPushResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lhotse.api.push.DataPush.DataPushResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lhotse.api.push.DataPush.DataPushResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lhotse.api.push.DataPush.DataPushResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lhotse.api.push.DataPush.DataPushResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.lhotse.api.push.DataPush.DataPushResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lhotse.api.push.DataPush.DataPushResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lhotse.api.push.DataPush.DataPushResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.lhotse.api.push.DataPush.DataPushResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 推送结果
     * </pre>
     *
     * Protobuf type {@code lhotse.networking.v1alpha1.DataPushResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lhotse.networking.v1alpha1.DataPushResponse)
        com.lhotse.api.push.DataPush.DataPushResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lhotse.api.push.DataPush.internal_static_lhotse_networking_v1alpha1_DataPushResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lhotse.api.push.DataPush.internal_static_lhotse_networking_v1alpha1_DataPushResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lhotse.api.push.DataPush.DataPushResponse.class, com.lhotse.api.push.DataPush.DataPushResponse.Builder.class);
      }

      // Construct using com.lhotse.api.push.DataPush.DataPushResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        status_ = 0;

        message_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lhotse.api.push.DataPush.internal_static_lhotse_networking_v1alpha1_DataPushResponse_descriptor;
      }

      @java.lang.Override
      public com.lhotse.api.push.DataPush.DataPushResponse getDefaultInstanceForType() {
        return com.lhotse.api.push.DataPush.DataPushResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.lhotse.api.push.DataPush.DataPushResponse build() {
        com.lhotse.api.push.DataPush.DataPushResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.lhotse.api.push.DataPush.DataPushResponse buildPartial() {
        com.lhotse.api.push.DataPush.DataPushResponse result = new com.lhotse.api.push.DataPush.DataPushResponse(this);
        result.status_ = status_;
        result.message_ = message_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lhotse.api.push.DataPush.DataPushResponse) {
          return mergeFrom((com.lhotse.api.push.DataPush.DataPushResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lhotse.api.push.DataPush.DataPushResponse other) {
        if (other == com.lhotse.api.push.DataPush.DataPushResponse.getDefaultInstance()) return this;
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lhotse.api.push.DataPush.DataPushResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lhotse.api.push.DataPush.DataPushResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int status_ = 0;
      /**
       * <pre>
       * 状态
       * </pre>
       *
       * <code>.lhotse.networking.v1alpha1.PushStatus status = 1 [json_name = "status"];</code>
       * @return The enum numeric value on the wire for status.
       */
      @java.lang.Override public int getStatusValue() {
        return status_;
      }
      /**
       * <pre>
       * 状态
       * </pre>
       *
       * <code>.lhotse.networking.v1alpha1.PushStatus status = 1 [json_name = "status"];</code>
       * @param value The enum numeric value on the wire for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusValue(int value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 状态
       * </pre>
       *
       * <code>.lhotse.networking.v1alpha1.PushStatus status = 1 [json_name = "status"];</code>
       * @return The status.
       */
      @java.lang.Override
      public com.lhotse.api.push.DataPush.PushStatus getStatus() {
        @SuppressWarnings("deprecation")
        com.lhotse.api.push.DataPush.PushStatus result = com.lhotse.api.push.DataPush.PushStatus.valueOf(status_);
        return result == null ? com.lhotse.api.push.DataPush.PushStatus.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 状态
       * </pre>
       *
       * <code>.lhotse.networking.v1alpha1.PushStatus status = 1 [json_name = "status"];</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(com.lhotse.api.push.DataPush.PushStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 状态
       * </pre>
       *
       * <code>.lhotse.networking.v1alpha1.PushStatus status = 1 [json_name = "status"];</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <pre>
       * 消息
       * </pre>
       *
       * <code>string message = 2 [json_name = "message"];</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 消息
       * </pre>
       *
       * <code>string message = 2 [json_name = "message"];</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 消息
       * </pre>
       *
       * <code>string message = 2 [json_name = "message"];</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息
       * </pre>
       *
       * <code>string message = 2 [json_name = "message"];</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息
       * </pre>
       *
       * <code>string message = 2 [json_name = "message"];</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:lhotse.networking.v1alpha1.DataPushResponse)
    }

    // @@protoc_insertion_point(class_scope:lhotse.networking.v1alpha1.DataPushResponse)
    private static final com.lhotse.api.push.DataPush.DataPushResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.lhotse.api.push.DataPush.DataPushResponse();
    }

    public static com.lhotse.api.push.DataPush.DataPushResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DataPushResponse>
        PARSER = new com.google.protobuf.AbstractParser<DataPushResponse>() {
      @java.lang.Override
      public DataPushResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DataPushResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DataPushResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DataPushResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.lhotse.api.push.DataPush.DataPushResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lhotse_networking_v1alpha1_DataPushRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lhotse_networking_v1alpha1_DataPushRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lhotse_networking_v1alpha1_DataPushResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lhotse_networking_v1alpha1_DataPushResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023push/DataPush.proto\022\032lhotse.networking" +
      ".v1alpha1\032\031google/protobuf/any.proto\"\301\001\n" +
      "\017DataPushRequest\022D\n\010category\030\001 \001(\0162(.lho" +
      "tse.networking.v1alpha1.DataCategoryR\010ca" +
      "tegory\022>\n\006action\030\002 \001(\0162&.lhotse.networki" +
      "ng.v1alpha1.PushActionR\006action\022(\n\004data\030\003" +
      " \001(\0132\024.google.protobuf.AnyR\004data\"l\n\020Data" +
      "PushResponse\022>\n\006status\030\001 \001(\0162&.lhotse.ne" +
      "tworking.v1alpha1.PushStatusR\006status\022\030\n\007" +
      "message\030\002 \001(\tR\007message*\275\001\n\014DataCategory\022" +
      "\031\n\025DATA_CATEGORY_SERVICE\020\000\022\031\n\025DATA_CATEG" +
      "ORY_CLUSTER\020\001\022\032\n\026DATA_CATEGORY_ENDPOINT\020" +
      "\002\022\026\n\022DATA_CATEGORY_RULE\020\003\022\034\n\030DATA_CATEGO" +
      "RY_AGENT_META\020\004\022%\n!DATA_CATEGORY_AGENT_U" +
      "PLOAD_STATUS\020\005*6\n\nPushStatus\022\022\n\016PUSH_STA" +
      "TUS_OK\020\000\022\024\n\020PUSH_STATUS_FAIL\020\001*=\n\nPushAc" +
      "tion\022\024\n\020PUSH_ACTION_FULL\020\000\022\031\n\025PUSH_ACTIO" +
      "N_INCREMENT\020\0012x\n\013PushService\022i\n\010PushData" +
      "\022+.lhotse.networking.v1alpha1.DataPushRe" +
      "quest\032,.lhotse.networking.v1alpha1.DataP" +
      "ushResponse(\0010\001B&\n\023com.lhotse.api.pushZ\017" +
      "lhotse/api/pushb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_lhotse_networking_v1alpha1_DataPushRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lhotse_networking_v1alpha1_DataPushRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lhotse_networking_v1alpha1_DataPushRequest_descriptor,
        new java.lang.String[] { "Category", "Action", "Data", });
    internal_static_lhotse_networking_v1alpha1_DataPushResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_lhotse_networking_v1alpha1_DataPushResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lhotse_networking_v1alpha1_DataPushResponse_descriptor,
        new java.lang.String[] { "Status", "Message", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
