// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agent/metadata.proto

package agent

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AgentMeta struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentMeta) Reset()         { *m = AgentMeta{} }
func (m *AgentMeta) String() string { return proto.CompactTextString(m) }
func (*AgentMeta) ProtoMessage()    {}
func (*AgentMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa374ed0cab9a9d7, []int{0}
}

func (m *AgentMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentMeta.Unmarshal(m, b)
}
func (m *AgentMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentMeta.Marshal(b, m, deterministic)
}
func (m *AgentMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentMeta.Merge(m, src)
}
func (m *AgentMeta) XXX_Size() int {
	return xxx_messageInfo_AgentMeta.Size(m)
}
func (m *AgentMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentMeta.DiscardUnknown(m)
}

var xxx_messageInfo_AgentMeta proto.InternalMessageInfo

func (m *AgentMeta) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto.RegisterType((*AgentMeta)(nil), "lhotse.api.agent.AgentMeta")
}

func init() { proto.RegisterFile("agent/metadata.proto", fileDescriptor_fa374ed0cab9a9d7) }

var fileDescriptor_fa374ed0cab9a9d7 = []byte{
	// 117 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x49, 0x4c, 0x4f, 0xcd,
	0x2b, 0xd1, 0xcf, 0x4d, 0x2d, 0x49, 0x4c, 0x49, 0x2c, 0x49, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0x12, 0xc8, 0xc9, 0xc8, 0x2f, 0x29, 0x4e, 0xd5, 0x4b, 0x2c, 0xc8, 0xd4, 0x03, 0x2b, 0x50,
	0x52, 0xe5, 0xe2, 0x74, 0x04, 0x31, 0x7c, 0x53, 0x4b, 0x12, 0x85, 0x24, 0xb8, 0xd8, 0xcb, 0x52,
	0x8b, 0x8a, 0x33, 0xf3, 0xf3, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x60, 0x5c, 0x27, 0x0d,
	0x2e, 0x91, 0xe4, 0xfc, 0x5c, 0x3d, 0x74, 0xed, 0x51, 0x50, 0x03, 0xf5, 0x13, 0x0b, 0x32, 0xf5,
	0xc1, 0x22, 0x49, 0x6c, 0x60, 0x9b, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x44, 0x18, 0x83,
	0xed, 0x81, 0x00, 0x00, 0x00,
}
