// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        (unknown)
// source: push/DataPush.proto

package push

import (
	any "github.com/golang/protobuf/ptypes/any"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataCategory int32

const (
	DataCategory_DATA_CATEGORY_SERVICE             DataCategory = 0
	DataCategory_DATA_CATEGORY_CLUSTER             DataCategory = 1
	DataCategory_DATA_CATEGORY_ENDPOINT            DataCategory = 2
	DataCategory_DATA_CATEGORY_RULE                DataCategory = 3
	DataCategory_DATA_CATEGORY_AGENT_META          DataCategory = 4
	DataCategory_DATA_CATEGORY_AGENT_UPLOAD_STATUS DataCategory = 5
)

// Enum value maps for DataCategory.
var (
	DataCategory_name = map[int32]string{
		0: "DATA_CATEGORY_SERVICE",
		1: "DATA_CATEGORY_CLUSTER",
		2: "DATA_CATEGORY_ENDPOINT",
		3: "DATA_CATEGORY_RULE",
		4: "DATA_CATEGORY_AGENT_META",
		5: "DATA_CATEGORY_AGENT_UPLOAD_STATUS",
	}
	DataCategory_value = map[string]int32{
		"DATA_CATEGORY_SERVICE":             0,
		"DATA_CATEGORY_CLUSTER":             1,
		"DATA_CATEGORY_ENDPOINT":            2,
		"DATA_CATEGORY_RULE":                3,
		"DATA_CATEGORY_AGENT_META":          4,
		"DATA_CATEGORY_AGENT_UPLOAD_STATUS": 5,
	}
)

func (x DataCategory) Enum() *DataCategory {
	p := new(DataCategory)
	*p = x
	return p
}

func (x DataCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_push_DataPush_proto_enumTypes[0].Descriptor()
}

func (DataCategory) Type() protoreflect.EnumType {
	return &file_push_DataPush_proto_enumTypes[0]
}

func (x DataCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataCategory.Descriptor instead.
func (DataCategory) EnumDescriptor() ([]byte, []int) {
	return file_push_DataPush_proto_rawDescGZIP(), []int{0}
}

type PushStatus int32

const (
	PushStatus_PUSH_STATUS_OK   PushStatus = 0
	PushStatus_PUSH_STATUS_FAIL PushStatus = 1
)

// Enum value maps for PushStatus.
var (
	PushStatus_name = map[int32]string{
		0: "PUSH_STATUS_OK",
		1: "PUSH_STATUS_FAIL",
	}
	PushStatus_value = map[string]int32{
		"PUSH_STATUS_OK":   0,
		"PUSH_STATUS_FAIL": 1,
	}
)

func (x PushStatus) Enum() *PushStatus {
	p := new(PushStatus)
	*p = x
	return p
}

func (x PushStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PushStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_push_DataPush_proto_enumTypes[1].Descriptor()
}

func (PushStatus) Type() protoreflect.EnumType {
	return &file_push_DataPush_proto_enumTypes[1]
}

func (x PushStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PushStatus.Descriptor instead.
func (PushStatus) EnumDescriptor() ([]byte, []int) {
	return file_push_DataPush_proto_rawDescGZIP(), []int{1}
}

// 推送动作
type PushAction int32

const (
	PushAction_PUSH_ACTION_FULL      PushAction = 0 // 全量
	PushAction_PUSH_ACTION_INCREMENT PushAction = 1 // 增量
)

// Enum value maps for PushAction.
var (
	PushAction_name = map[int32]string{
		0: "PUSH_ACTION_FULL",
		1: "PUSH_ACTION_INCREMENT",
	}
	PushAction_value = map[string]int32{
		"PUSH_ACTION_FULL":      0,
		"PUSH_ACTION_INCREMENT": 1,
	}
)

func (x PushAction) Enum() *PushAction {
	p := new(PushAction)
	*p = x
	return p
}

func (x PushAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PushAction) Descriptor() protoreflect.EnumDescriptor {
	return file_push_DataPush_proto_enumTypes[2].Descriptor()
}

func (PushAction) Type() protoreflect.EnumType {
	return &file_push_DataPush_proto_enumTypes[2]
}

func (x PushAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PushAction.Descriptor instead.
func (PushAction) EnumDescriptor() ([]byte, []int) {
	return file_push_DataPush_proto_rawDescGZIP(), []int{2}
}

// 推送请求
type DataPushRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category DataCategory `protobuf:"varint,1,opt,name=category,proto3,enum=lhotse.networking.v1alpha1.DataCategory" json:"category,omitempty"` // 数据类型
	Data     *any.Any     `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                                                       // 数据
}

func (x *DataPushRequest) Reset() {
	*x = DataPushRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_push_DataPush_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataPushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPushRequest) ProtoMessage() {}

func (x *DataPushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_push_DataPush_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPushRequest.ProtoReflect.Descriptor instead.
func (*DataPushRequest) Descriptor() ([]byte, []int) {
	return file_push_DataPush_proto_rawDescGZIP(), []int{0}
}

func (x *DataPushRequest) GetCategory() DataCategory {
	if x != nil {
		return x.Category
	}
	return DataCategory_DATA_CATEGORY_SERVICE
}

func (x *DataPushRequest) GetData() *any.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

type ServerDataPushRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action   PushAction `protobuf:"varint,1,opt,name=action,proto3,enum=lhotse.networking.v1alpha1.PushAction" json:"action,omitempty"` // 动作
	Checksum string     `protobuf:"bytes,2,opt,name=checksum,proto3" json:"checksum,omitempty"`                                         //校验和
	Revision string     `protobuf:"bytes,3,opt,name=revision,proto3" json:"revision,omitempty"`                                         //修订版本
	Data     *any.Any   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`                                                 // 数据
}

func (x *ServerDataPushRequest) Reset() {
	*x = ServerDataPushRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_push_DataPush_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerDataPushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerDataPushRequest) ProtoMessage() {}

func (x *ServerDataPushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_push_DataPush_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerDataPushRequest.ProtoReflect.Descriptor instead.
func (*ServerDataPushRequest) Descriptor() ([]byte, []int) {
	return file_push_DataPush_proto_rawDescGZIP(), []int{1}
}

func (x *ServerDataPushRequest) GetAction() PushAction {
	if x != nil {
		return x.Action
	}
	return PushAction_PUSH_ACTION_FULL
}

func (x *ServerDataPushRequest) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *ServerDataPushRequest) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *ServerDataPushRequest) GetData() *any.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

// 推送结果
type DataPushResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  PushStatus `protobuf:"varint,1,opt,name=status,proto3,enum=lhotse.networking.v1alpha1.PushStatus" json:"status,omitempty"` // 状态
	Message string     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                           // 消息
}

func (x *DataPushResponse) Reset() {
	*x = DataPushResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_push_DataPush_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataPushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPushResponse) ProtoMessage() {}

func (x *DataPushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_push_DataPush_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPushResponse.ProtoReflect.Descriptor instead.
func (*DataPushResponse) Descriptor() ([]byte, []int) {
	return file_push_DataPush_proto_rawDescGZIP(), []int{2}
}

func (x *DataPushResponse) GetStatus() PushStatus {
	if x != nil {
		return x.Status
	}
	return PushStatus_PUSH_STATUS_OK
}

func (x *DataPushResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Agent启动上报身份信息
type AgentRegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *AgentRegisterRequest) Reset() {
	*x = AgentRegisterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_push_DataPush_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRegisterRequest) ProtoMessage() {}

func (x *AgentRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_push_DataPush_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRegisterRequest.ProtoReflect.Descriptor instead.
func (*AgentRegisterRequest) Descriptor() ([]byte, []int) {
	return file_push_DataPush_proto_rawDescGZIP(), []int{3}
}

func (x *AgentRegisterRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentRegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_push_DataPush_proto protoreflect.FileDescriptor

var file_push_DataPush_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x75, 0x73, 0x68, 0x2f, 0x44, 0x61, 0x74, 0x61, 0x50, 0x75, 0x73, 0x68, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x6c, 0x68, 0x6f, 0x74, 0x73, 0x65, 0x2e, 0x6e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x31, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x81, 0x01, 0x0a,
	0x0f, 0x44, 0x61, 0x74, 0x61, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x44, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x28, 0x2e, 0x6c, 0x68, 0x6f, 0x74, 0x73, 0x65, 0x2e, 0x6e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e,
	0x44, 0x61, 0x74, 0x61, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x08, 0x63, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0xb9, 0x01, 0x0a, 0x15, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x50,
	0x75, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3e, 0x0a, 0x06, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x26, 0x2e, 0x6c, 0x68, 0x6f,
	0x74, 0x73, 0x65, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x76,
	0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x68,
	0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x68,
	0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x6c, 0x0a, 0x10,
	0x44, 0x61, 0x74, 0x61, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3e, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x26, 0x2e, 0x6c, 0x68, 0x6f, 0x74, 0x73, 0x65, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x50, 0x75,
	0x73, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x4b, 0x0a, 0x14, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x2a, 0xbd, 0x01, 0x0a, 0x0c, 0x44, 0x61, 0x74, 0x61,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x19, 0x0a, 0x15, 0x44, 0x41, 0x54, 0x41,
	0x5f, 0x43, 0x41, 0x54, 0x45, 0x47, 0x4f, 0x52, 0x59, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43,
	0x45, 0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x43, 0x41, 0x54, 0x45,
	0x47, 0x4f, 0x52, 0x59, 0x5f, 0x43, 0x4c, 0x55, 0x53, 0x54, 0x45, 0x52, 0x10, 0x01, 0x12, 0x1a,
	0x0a, 0x16, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x43, 0x41, 0x54, 0x45, 0x47, 0x4f, 0x52, 0x59, 0x5f,
	0x45, 0x4e, 0x44, 0x50, 0x4f, 0x49, 0x4e, 0x54, 0x10, 0x02, 0x12, 0x16, 0x0a, 0x12, 0x44, 0x41,
	0x54, 0x41, 0x5f, 0x43, 0x41, 0x54, 0x45, 0x47, 0x4f, 0x52, 0x59, 0x5f, 0x52, 0x55, 0x4c, 0x45,
	0x10, 0x03, 0x12, 0x1c, 0x0a, 0x18, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x43, 0x41, 0x54, 0x45, 0x47,
	0x4f, 0x52, 0x59, 0x5f, 0x41, 0x47, 0x45, 0x4e, 0x54, 0x5f, 0x4d, 0x45, 0x54, 0x41, 0x10, 0x04,
	0x12, 0x25, 0x0a, 0x21, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x43, 0x41, 0x54, 0x45, 0x47, 0x4f, 0x52,
	0x59, 0x5f, 0x41, 0x47, 0x45, 0x4e, 0x54, 0x5f, 0x55, 0x50, 0x4c, 0x4f, 0x41, 0x44, 0x5f, 0x53,
	0x54, 0x41, 0x54, 0x55, 0x53, 0x10, 0x05, 0x2a, 0x36, 0x0a, 0x0a, 0x50, 0x75, 0x73, 0x68, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x0e, 0x50, 0x55, 0x53, 0x48, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x55, 0x53, 0x5f, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x50, 0x55, 0x53,
	0x48, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x10, 0x01, 0x2a,
	0x3d, 0x0a, 0x0a, 0x50, 0x75, 0x73, 0x68, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a,
	0x10, 0x50, 0x55, 0x53, 0x48, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x46, 0x55, 0x4c,
	0x4c, 0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x50, 0x55, 0x53, 0x48, 0x5f, 0x41, 0x43, 0x54, 0x49,
	0x4f, 0x4e, 0x5f, 0x49, 0x4e, 0x43, 0x52, 0x45, 0x4d, 0x45, 0x4e, 0x54, 0x10, 0x01, 0x32, 0x78,
	0x0a, 0x0b, 0x50, 0x75, 0x73, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x69, 0x0a,
	0x08, 0x50, 0x75, 0x73, 0x68, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2b, 0x2e, 0x6c, 0x68, 0x6f, 0x74,
	0x73, 0x65, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x50, 0x75, 0x73, 0x68, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x6c, 0x68, 0x6f, 0x74, 0x73, 0x65, 0x2e,
	0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70,
	0x68, 0x61, 0x31, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x26, 0x0a, 0x13, 0x63, 0x6f, 0x6d, 0x2e,
	0x6c, 0x68, 0x6f, 0x74, 0x73, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x5a,
	0x0f, 0x6c, 0x68, 0x6f, 0x74, 0x73, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x75, 0x73, 0x68,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_push_DataPush_proto_rawDescOnce sync.Once
	file_push_DataPush_proto_rawDescData = file_push_DataPush_proto_rawDesc
)

func file_push_DataPush_proto_rawDescGZIP() []byte {
	file_push_DataPush_proto_rawDescOnce.Do(func() {
		file_push_DataPush_proto_rawDescData = protoimpl.X.CompressGZIP(file_push_DataPush_proto_rawDescData)
	})
	return file_push_DataPush_proto_rawDescData
}

var file_push_DataPush_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_push_DataPush_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_push_DataPush_proto_goTypes = []interface{}{
	(DataCategory)(0),             // 0: lhotse.networking.v1alpha1.DataCategory
	(PushStatus)(0),               // 1: lhotse.networking.v1alpha1.PushStatus
	(PushAction)(0),               // 2: lhotse.networking.v1alpha1.PushAction
	(*DataPushRequest)(nil),       // 3: lhotse.networking.v1alpha1.DataPushRequest
	(*ServerDataPushRequest)(nil), // 4: lhotse.networking.v1alpha1.ServerDataPushRequest
	(*DataPushResponse)(nil),      // 5: lhotse.networking.v1alpha1.DataPushResponse
	(*AgentRegisterRequest)(nil),  // 6: lhotse.networking.v1alpha1.AgentRegisterRequest
	(*any.Any)(nil),               // 7: google.protobuf.Any
}
var file_push_DataPush_proto_depIdxs = []int32{
	0, // 0: lhotse.networking.v1alpha1.DataPushRequest.category:type_name -> lhotse.networking.v1alpha1.DataCategory
	7, // 1: lhotse.networking.v1alpha1.DataPushRequest.data:type_name -> google.protobuf.Any
	2, // 2: lhotse.networking.v1alpha1.ServerDataPushRequest.action:type_name -> lhotse.networking.v1alpha1.PushAction
	7, // 3: lhotse.networking.v1alpha1.ServerDataPushRequest.data:type_name -> google.protobuf.Any
	1, // 4: lhotse.networking.v1alpha1.DataPushResponse.status:type_name -> lhotse.networking.v1alpha1.PushStatus
	3, // 5: lhotse.networking.v1alpha1.PushService.PushData:input_type -> lhotse.networking.v1alpha1.DataPushRequest
	5, // 6: lhotse.networking.v1alpha1.PushService.PushData:output_type -> lhotse.networking.v1alpha1.DataPushResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_push_DataPush_proto_init() }
func file_push_DataPush_proto_init() {
	if File_push_DataPush_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_push_DataPush_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataPushRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_push_DataPush_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerDataPushRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_push_DataPush_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataPushResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_push_DataPush_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentRegisterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_push_DataPush_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_push_DataPush_proto_goTypes,
		DependencyIndexes: file_push_DataPush_proto_depIdxs,
		EnumInfos:         file_push_DataPush_proto_enumTypes,
		MessageInfos:      file_push_DataPush_proto_msgTypes,
	}.Build()
	File_push_DataPush_proto = out.File
	file_push_DataPush_proto_rawDesc = nil
	file_push_DataPush_proto_goTypes = nil
	file_push_DataPush_proto_depIdxs = nil
}
